export const workshopErrorCodes = {
  PROJECT_EXISTS: 'WORKSHOP_PROJECT_EXISTS',
  NOT_A_PROJECT: 'WORKSHOP_NOT_A_PROJECT',
  INVALID_CHANGESET: 'WORKSHOP_INVALID_CHANGESET',
  CHAPTER_NOT_FOUND: 'WORKSHOP_CHAPTER_NOT_FOUND',
  ENTITY_NOT_FOUND: 'WORKSHOP_ENTITY_NOT_FOUND',
  PROPOSAL_NOT_FOUND: 'WORKSHOP_PROPOSAL_NOT_FOUND',
  PROPOSAL_NOT_PENDING: 'WORKSHOP_PROPOSAL_NOT_PENDING',
  PROPOSAL_STALE: 'WORKSHOP_PROPOSAL_STALE',
  ROLLBACK_TARGET_INVALID: 'WORKSHOP_ROLLBACK_TARGET_INVALID'
} as const

export type WorkshopErrorCode = (typeof workshopErrorCodes)[keyof typeof workshopErrorCodes]
