export const writerErrorCodes = {
  PROJECT_NOT_FOUND: 'WRITER_PROJECT_NOT_FOUND',
  PROJECT_ALREADY_EXISTS: 'WRITER_PROJECT_ALREADY_EXISTS',
  INVALID_PROJECT: 'WRITER_INVALID_PROJECT',
  CHAPTER_NOT_FOUND: 'WRITER_CHAPTER_NOT_FOUND',
  REVISION_CONFLICT: 'WRITER_REVISION_CONFLICT',
  PATH_OUTSIDE_PROJECT: 'WRITER_PATH_OUTSIDE_PROJECT',
  PROPOSAL_NOT_FOUND: 'WRITER_PROPOSAL_NOT_FOUND',
  HISTORY_NOT_FOUND: 'WRITER_HISTORY_NOT_FOUND',
  PROPOSAL_ALREADY_APPLIED: 'WRITER_PROPOSAL_ALREADY_APPLIED',
  PROPOSAL_MODE_NOT_ALLOWED: 'WRITER_PROPOSAL_MODE_NOT_ALLOWED',
  MODEL_UNAVAILABLE: 'WRITER_MODEL_UNAVAILABLE',
  CONTEXT_BUDGET_EXHAUSTED: 'WRITER_CONTEXT_BUDGET_EXHAUSTED',
  CONTINUITY_FINDING_NOT_FOUND: 'WRITER_CONTINUITY_FINDING_NOT_FOUND',
  CONTINUITY_FINDING_NOT_EXEMPTIBLE: 'WRITER_CONTINUITY_FINDING_NOT_EXEMPTIBLE',
  CONTINUITY_CHECK_FAILED: 'WRITER_CONTINUITY_CHECK_FAILED',
  INVALID_PROPOSAL: 'WRITER_INVALID_PROPOSAL'
} as const

export type WriterErrorCode = (typeof writerErrorCodes)[keyof typeof writerErrorCodes]
